CREATE TABLE IF NOT EXISTS cars
(
    car_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vin VARCHAR(124)                               NOT NULL,
    government_number VARCHAR(64)                  NOT NULL,
    manufacturer VARCHAR(255),
    brand VARCHAR(255),
    year_of_issue timestamp without time zone      not null,
    owner_id BIGINT,
    CONSTRAINT pk_cars primary key (car_id),
    CONSTRAINT UQ_VIN UNIQUE (vin)
    );

CREATE TABLE IF NOT EXISTS details
(
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_number VARCHAR(124)                        NOT NULL,
    denomination VARCHAR(124)                         NOT NULL,
    car_id BIGINT,
    CONSTRAINT pk_categories primary key (detail_id),
    CONSTRAINT UQ_serial_number UNIQUE (serial_number),
    CONSTRAINT FK_CAR_DETAIL FOREIGN KEY (car_id) REFERENCES cars (car_id) ON DELETE CASCADE
    );